export const tabella_conversioni_generi = {
  "ART": "Arte",
  "PERFORMING ARTS": "Arti Rappresentative",
  "DESIGN": "Design",
  "PHOTOGRAPHY": "Fotografia",
  "MUSIC": "Musica",
  "BIBLES": "Bibbie",
  "BIOGRAPHY & AUTOBIOGRAPHY": "Biografia e Autobiografia",
  "BODY, MIND & SPIRIT": "Corpo, Mente e Spirito",
  "TRUE CRIME": "Crimine Reale",
  "LITERARY CRITICISM": "Critica Letteraria",
  "EDUCATION": "Educazione",
  "PHILOSOPHY": "Filosofia",
  "LAW": "Giurisprudenza",
  "MATHEMATICS": "Matematica",
  "MEDICAL": "Medico",
  "NATURE": "Natura",
  "PSYCHOLOGY": "Psicologia",
  "RELIGION": "Religione",
  "SCIENCE": "Scienza",
  "POLITICAL SCIENCE": "Scienze Politiche",
  "SOCIAL SCIENCE": "Scienze Sociali",
  "HISTORY": "Storia",
  "PETS": "Animali Domestici",
  "ARCHITECTURE": "Architettura",
  "SELF-HELP": "Auto-Aiuto",
  "BUSINESS & ECONOMICS": "Business ed Economia",
  "HOUSE & HOME": "Casa e Abitazione",
  "ANTIQUES & COLLECTIBLES": "Collezionismo e Antiquariato",
  "COMPUTERS": "Informatica",
  "COOKING": "Cucina",
  "FAMILY & RELATIONSHIPS": "Famiglia e Relazioni",
  "GARDENING": "Giardinaggio",
  "GAMES & ACTIVITIES": "Giochi e Attività",
  "CRAFTS & HOBBIES": "Hobby e Creatività",
  "HEALTH & FITNESS": "Salute e Fitness",
  "SPORTS & RECREATION": "Sport e Svago",
  "TECHNOLOGY & ENGINEERING": "Tecnologia e Ingegneria",
  "TRANSPORTATION": "Trasporto",
  "TRAVEL": "Viaggi",
  "LANGUAGE ARTS & DISCIPLINES": "Arti e Discipline Linguistiche",
  "LITERARY COLLECTIONS": "Collezioni Letterarie",
  "DRAMA": "Drammatico",
  "FICTION": "Narrativa",
  "COMICS & GRAPHIC NOVELS": "Fumetti e Romanzi Illustrati",
  "POETRY": "Poesia",
  "LANGUAGE STUDY": "Studio della Lingua Straniera",
  "HUMOR": "Umorismo",
  "JUVENILE FICTION": "Fiction per Ragazzi",
  "JUVENILE NONFICTION": "Non-Fiction per Ragazzi",
  "STUDY AIDS": "Supporti Didattici",
  "YOUNG ADULT FICTION": "Young Adult Fiction (Narrativa per Giovani Adulti)",
  "YOUNG ADULT NONFICTION": "Young Adult Nonfiction (Saggistica per Giovani Adulti)",
  "REFERENCE": "Riferimento"
}